newGames/api/urls.py
from django.urls import re_path
import api.views as api

app_name = 'api'

urlpatterns = [

]

newGames/newGames/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('user.urls', namespace='user')),
    path('post/', include('post.urls', namespace='post')),
    path('', include('new.urls', namespace='new')),
    path('api/', include('api.urls', namespace='api')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

newGames/user/urls.py
from django.urls import re_path
import user.views as user

app_name = 'user'

urlpatterns = [
    re_path('login/$', user.user_login, name='login'),
    re_path('register/$', user.user_register, name='register'),
    re_path('edit/$', user.user_edit, name='edit'),
    re_path('logout/$', user.user_logout, name='logout'),
    re_path('profile/(?P<url_id>.*\s*)/$', user.user_profile, name='profile'),
]

newGames/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block title %}
        <title>{if title_page_name}</title>
    {% endblock %}
    <link rel="stylesheet" href="/static/css/base.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    {% block css %}
    {% endblock %}
</head>
<body>
    <header>
<!--        <div class="block-menu"></div>-->
        <div class="logo">GameNews</div>

        <div class="input-output">
        {% if user.is_authenticated %}
            <a class="{% if request.resolver_match.url_name == 'logout' %}active{% endif %}"
                                                                href="{% url 'user:logout' %}">
                <span class="login-span">Выйти</span>
            </a>
        {% else %}
            <a class="{% if request.resolver_match.url_name == 'login' %}active{% endif %}"
                                                                href="{% url 'user:login' %}">
                <span class="login-span">Войти</span>
            </a>
        {% endif %}
        </div>
    </header>
    <div class="content">
    {% block content %}
    {% endblock %}
    </div>
    <footer>
        <span class="years">
            {% now "Y" %}
        </span>
        <span class="tagline">
            "GameNews"
        </span>
    </footer>
    <script src="static/js/jquery-3.6.4.min.js"></script>
    {% block script %}
    {% endblock %}
</body>
</html>